### ISSUE TITLE
Didn't creat a txt file

### ISSUE THREAD

**Issue by Flawyy** [sp0ok3r/ChatLogger#1]
Hello,
soo... The Program doesn't save anything.
It starts perfectly and im logged in but somehow it didn't create a single txt file with the chat
I hope u can help me out.

**Comment by sp0ok3r** [comment]
Hello, what version are you using?

**Comment by Flawyy** [comment]
Im currently using the newest version

**Comment by sp0ok3r** [comment]
send me your steam link

**Comment by Flawyy** [comment]
https://steamcommunity.com/id/pointlessdrug/ This is it

Am Sa., 18. Mai 2019 um 11:38 Uhr schrieb sp0ok3r <notifications@github.com

**Comment by Flawyy** [comment]
https://steamcommunity.com/id/pointlessdrug/ This is it

**Comment by sp0ok3r** [comment]
#solved
