### ISSUE TITLE
Not writing the log (txt) files

### ISSUE THREAD

**Issue by Venima** [sp0ok3r/ChatLogger#10]
I'm logged in, it says recording, I can open the log folder but it isn't writing any of the txt files.

I'm using version 1.0.3b.

**Comment by sp0ok3r** [comment]
add me https://steamcommunity.com/id/sp0ok3rz/

**Comment by Venima** [comment]
Invite sent. You should recognise my pfp and name.

**Comment by sp0ok3r** [comment]
*Windows 7 Related*

**Comment by sp0ok3r** [comment]
#fixed - clean path folder with clean perms
