### ISSUE TITLE
Can't log in.

### ISSUE THREAD

**Issue by Binol-PL** [sp0ok3r/ChatLogger#13]
Hi,
I can't login in Chat Logger. Im 100% sure of user id and pass, but still after some time app show me this error:
https://bit.ly/2Wh00ip

App worked for few days, 2 days ago stopped.

**Comment by sp0ok3r** [comment]
This is internet issues, your steam might be down

**Comment by Binol-PL** [comment]
My steam works fine while i try to log into chat logger app. It's not this for sure.
