### ISSUE TITLE
Doesn't record anything since April

### ISSUE THREAD

**Issue by CodeSpartan** [sp0ok3r/ChatLogger#15]
I'm on version 1.0.3c, still doesn't record.
What other information can I provide for this report?

**Comment by sp0ok3r** [comment]
What windows are you using?

**Comment by CodeSpartan** [comment]
> 
> 
> What windows are you using?

Windows 10 Pro, 64 bit.
I can compile from source and set up breakpoints if necessary, or anything like that.

**Comment by sp0ok3r** [comment]
yes, but can you try my other project? [https://github.com/sp0ok3r/Mercury](Mercury) , and see if the chatlogger works

**Comment by sp0ok3r** [comment]
add me on steam https://steamcommunity.com/id/sp0ok3rz/

**Comment by echotango2019** [comment]
Does

**Comment by echotango2019** [comment]
Does that new chat logger work?

**Comment by sp0ok3r** [comment]
yes its working for me
