### ISSUE TITLE
Minor visual bug - missing nickname and part of profile image

### ISSUE THREAD

**Issue by troennes** [sp0ok3r/ChatLogger#16]
When Start with Windows, minimized and Hide in task bar options are on, part of the profile image, flag and nickname is missing when opening the program from the tray. See example image below:

![visual-bug](https://user-images.githubusercontent.com/2291639/99877429-7a641900-2bfe-11eb-972d-e90213aba3ad.png)

**Comment by sp0ok3r** [comment]
I will have a look into this

**Comment by sp0ok3r** [comment]
fixed
