### ISSUE TITLE
Not recording logs

### ISSUE THREAD

**Issue by ChrisHandsome** [sp0ok3r/ChatLogger#17]
Hello! First off, wanted to say that I really appreciate your chatlogger, it has been incredibly useful! I've ran into a problem recently where it seems to not be recording chat at all. I've logged in and out, closed and opened the application and even deleted settings and deleted my account. Each time I log in, I can log in fine but it isn't asking for authentication and it isn't recording chats. Do you know of any possible fix or is there any other troubleshooting I should try? Thank you!

**Comment by sp0ok3r** [comment]
Does this happen when steam is on maintenance every tuesday?

**Comment by ChrisHandsome** [comment]
Sometimes it stops recording when that happens and logging in and back out of the logger fixes it. Unfortunately right now, I haven't been able to fix it that way. I have been able to find a work around for now, where I changed the directory where the chat logs go.

**Comment by sp0ok3r** [comment]
I will have a look

**Comment by EsDeKa** [comment]
Started with testing the tool but I have the same issue I believe, were it randomly stops working, I noticed it stopped logging in the middle of a conversation
Or doesn't log anything at all after booting

**Comment by sp0ok3r** [comment]
Hello, can you try using Mercury and see if fails?

**Comment by ChrisHandsome** [comment]
Hey, sorry for the super late reply, I got notifications for this thread on a burner email lol. Mercury has been working really well and wanted to say I appreciate the help!

**Comment by sp0ok3r** [comment]
fixed
