### ISSUE TITLE
At random, it will stop logging and needs a reset to fix.

### ISSUE THREAD

**Issue by alsnana** [sp0ok3r/ChatLogger#2]
Not sure what causes it, I've tried nailing it down but after a while (30 minutes, an hour, not sure) it will stop logging text and I have to shut it down entirely and boot it up again to make it start over.

I think, not sure, logging out and in works too.

**Comment by sp0ok3r** [comment]
no errors?

**Comment by alsnana** [comment]
Sometimes I get "too many disconnects, try again in a few minutes" but most of the time I get no errors. IT just quietly stops logging

**Comment by sp0ok3r** [comment]
change it, and tell me progress

**Comment by sp0ok3r** [comment]
add me http://steamcommunity.com/profiles/76561198041931474

**Comment by sp0ok3r** [comment]
#solved_clientside
