### ISSUE TITLE
New update "Install" URL from within app never works, going to wrong URL.

### ISSUE THREAD

**Issue by Skyridr** [sp0ok3r/ChatLogger#20]
Every time I get an update request, the url appears to be wrong.

EG, the latest 1.0.4 url from within the app sends me to
https://github.com/sp0ok3r/ChatLogger/releases/latest/ChatLogger1.0.4.zip

Which doesn't exist, while the working github download url is https://github.com/sp0ok3r/ChatLogger/releases/download/1.0.4/ChatLogger1.0.4.zip

Possible this can be fixed for future releases? As this has been a small issue ever since I first installed the app that was a problem on previous versions as well.

**Comment by sp0ok3r** [comment]
In 1.0.4 this was already fixed
