### ISSUE TITLE
sp0ok3r.tk is down try https://github.com/sp0ok3r/

### ISSUE THREAD

**Issue by Chad90b** [sp0ok3r/ChatLogger#21]
does chatlogger require access to this sp0ok3r.tk site? spooky.
anyway the site seems to be down now and this force-quits chatlogger which now effective does not work sine the application closes or crashes upon this error.

![image](https://user-images.githubusercontent.com/68355086/129443789-8d418424-855d-418d-9857-b9fb39d0df29.png)

**Comment by sp0ok3r** [comment]
Im going to fix this

**Comment by sp0ok3r** [comment]
fixed, just download the 1.0.4 files again
