### ISSUE TITLE
Update window

### ISSUE THREAD

**Issue by Surica-11** [sp0ok3r/ChatLogger#4]
Hello~
So a new update is out, yay! I downloaded all the files and replaced them, update window still shows up, if I try to close it the whole app shuts down. 
Also deleting Accounts.json and Settings.json only gave me errors. 

Any suggestions on what to do?

**Comment by sp0ok3r** [comment]
When update windows shows up, did you click on [ install ]?

**Comment by sp0ok3r** [comment]
add me on http://steamcommunity.com/profiles/76561198041931474/

**Comment by Surica-11** [comment]
> When update windows shows up, did you click on [ install ]?

yea, it led me to two websites, one which only says "Not Found" and the other ones sends me to this file.

**Comment by sp0ok3r** [comment]
fixed*
