### ISSUE TITLE
1.02 refuses to startup now due to auto-update + 1.03 won't auto-login

### ISSUE THREAD

**Issue by BartyMae** [sp0ok3r/ChatLogger#5]
not great, bob

**Comment by sp0ok3r** [comment]
Gotcha, gonna fix this

**Comment by sp0ok3r** [comment]
Released new version [1.0.3a](https://github.com/sp0ok3r/ChatLogger/releases/tag/1.0.3a) !

**Comment by BartyMae** [comment]
thank you, works again
