### ISSUE TITLE
ignore username for log files

### ISSUE THREAD

**Issue by BartyMae** [sp0ok3r/ChatLogger#6]
I have a friend that changes their name a lot

https://dl.dropboxusercontent.com/s/43kklbghv0ncfsq/explorer_2020-01-27_22-15-46.png

this is less than ideal to search through, to say the least. it'd be nice if there was an option to ignore username so the same steamid always combined into the same chatlog file

**Comment by sp0ok3r** [comment]
I see, will check this today

**Comment by sp0ok3r** [comment]
Released new version [1.0.3a](https://github.com/sp0ok3r/ChatLogger/releases/tag/1.0.3a) !
