### ISSUE TITLE
"Spooker down"

### ISSUE THREAD

**Issue by BartyMae** [sp0ok3r/ChatLogger#7]
https://dl.dropboxusercontent.com/s/abs3zpuws5tlfo3/ChatLogger_2020-03-23_06-32-30.png

seems like a not great security/functionality idea to make it call home to a 3rd party to begin with, haha (...and especially because it just auto-closes right now because of it)

**Comment by sp0ok3r** [comment]
i only use sp0ok3r.tk to check version updates :D

**Comment by sp0ok3r** [comment]
#fixed
