### ISSUE TITLE
Log multi-line messages

### ISSUE THREAD

**Issue by AlexanderRitter02** [sp0ok3r/ChatLogger#8]
#### Problem
In Steam you can create a new line in a **single message** by doing SHIFT+Tab in the message field.

![steam multiline](https://user-images.githubusercontent.com/42546705/77966479-6c662e80-72e3-11ea-9d86-9d129bf45a71.png)

Currently the logger *removes* the new line and logs the message in the following way: `Line1Line2`

This is not ideal because **message history can't be reproduced in an authentic way.**
_It especially affects third-party programs that want to replay chat history or for example create a graphical representation that looks like the original chat._

#### Solution
This [[example-multiline.txt](https://github.com/sp0ok3r/ChatLogger/files/4405759/example-multiline.txt)] is how I think it should be saved. It's the same format WhatsApp uses in its export functionality.
```
[31.03.2020 00:15:02] steam-user: Line 1
Line 2
[31.03.2020 00:06:21] steam-user: This message is multi-line
It should be saved in a reproducible way
Users can still read it and a parsing program can deal with it fine
[31.03.2020 00:12:53] steam-user: This is a normal message
```

#### Code (propably)
Do regex magic and change the following line:
https://github.com/sp0ok3r/ChatLogger/blob/802f4d35fdf87b752cd1c65270a68c673c048e23/ChatLogger/AccountLogin.cs#L345

**Comment by sp0ok3r** [comment]
ok i will revert this! thanks for feedback

**Comment by sp0ok3r** [comment]
https://github.com/sp0ok3r/ChatLogger/releases/tag/1.0.3b

**Comment by AlexanderRitter02** [comment]
Thanks, I'm currently looking into generating `html` files with Steam styling from your (awesome) logs.
I may give more feedback soon, good to see your appreciating it. Currently the project is just in it's beginnings however.

**Comment by sp0ok3r** [comment]
That idea gave me another idea, like being able to see the logs inside the program with the same style of steam 👀

**Comment by AlexanderRitter02** [comment]
That's what I'm trying to archive. :wink: But a program UI is overkill for me (I'm learning a lot new). So I decided to go with the HTML approach.
The idea for html export is from this [Discord Logger](https://github.com/Tyrrrz/DiscordChatExporter), output pretty much looks like you have Discord open.

**Comment by AlexanderRitter02** [comment]
And a plus for HTML+CSS is that you can open it on any browser and propably many years from now.
But either way keeping the original `.txt` logs is the safest option for archiving.

**Comment by sp0ok3r** [comment]
add me https://steamcommunity.com/id/sp0ok3rz/
